spring:
  datasource:
    url: jdbc:mysql://mysql.stud.idi.ntnu.no:3306/tomaber
    username: tomaber
    password: h97.OqxwW
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true